### ISSUE TITLE
synthetic class not found error fix

### ISSUE THREAD

**Issue by unnaturalistic** [AfterglowMC/AfterglowMC#1]
hey, you need to fix your code buddy
copy the synthetic class found at the bottom of the minecraft.java file and move it to its separate file, then import it, so people can play your mod

**Comment by liminalityyy** [comment]
you can literally play the mod just fine, youre high as hell

**Comment by Vincent392** [comment]
> you can literally play the mod just fine, youre high as hell

fax, they launched V4 as V3.1 by mistake.
